apps/forum/urls.py
from django.conf.urls import url
from . import views

app_name = "forum"

urlpatterns = [
        url(r"^$",views.index,name="index"),
        url(r"^logout",views.logout,name="logout"),
        url(r"^(?P<forumName>.+)/$",views.forum,name="forum"),
        url(r"^newThread$",views.newThread,name="newThread"),
        url(r"^createThread$",views.createThread,name="createThread"),
        url(r"^thread/(?P<thread>.+)",views.showThread,name="showThread"),
        url(r"^post$",views.newPost,name="newPost"),
        url(r"^createForum",views.newForum,name="newForum"),
        
        ]

helpMyCat/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('apps.loginRegister.urls',namespace='loginRegister')),
    url(r'^forum/',include('apps.forum.urls',namespace='forum')),
    url(r'^map/',include('apps.map.urls',namespace="map")),
]

apps/forum/models.py
from __future__ import unicode_literals
from ..loginRegister.models import User 
from django.db import models

# Create your models here.
class Forum(models.Model):
    forum = models.CharField(max_length=45)
    description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Thread(models.Model):
    thread = models.CharField(max_length=255)
    forum = models.ForeignKey(Forum)
    creator = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Post(models.Model):
    post = models.TextField()
    thread = models.ForeignKey(Thread)
    writer = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/forum/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from .models import Forum, Thread, Post
from ..loginRegister.models import User
# Create your views here.
def index(request):
    allForum = Forum.objects.all()
    health = Forum.objects.get(forum="Cat Health")
    nutrition = Forum.objects.get(forum="Cat Nutrition")
    behavior = Forum.objects.get(forum="Cat Behavior")
    care = Forum.objects.get(forum="Cat Care & Grooming")
    new = Forum.objects.get(forum="New Cat")
    pregnant = Forum.objects.get(forum="Pregnant Cats")
    dog = Forum.objects.get(forum="Cats and Dogs")
    context={"allForum":allForum,
            "health":health,
            "nutrition":nutrition,
            "behavior":behavior,
            "care":care,
            "new":new,
            "pregnant":pregnant,
            "dog":dog,
            }
    return render(request,"forum/index.html",context)

def logout(request):
    request.session.pop("user")
    return redirect(reverse("loginRegister:index"))

def forum(request,forumName):
    currentForum = Forum.objects.get(forum=forumName)
    allThread = currentForum.thread_set.all()
    context = {"allThread":allThread}
    request.session["forum"] = forumName;
    return render(request,"forum/forum.html",context)

def newThread(request):
    currentForum = request.session["forum"]
    context = {"forum":currentForum}
    return render(request,"forum/newThread.html",context)

def createThread(request):
    if request.method=="POST":
        threadTitle = request.POST["thread"]
        creator = User.objects.get(username=request.session["user"])
        currentForum = Forum.objects.get(forum=request.session["forum"])
        newThread = Thread.objects.create(thread=threadTitle,forum=currentForum,creator=creator)
        newThread.save();
        currentForum.thread_set.add(newThread)
        currentForum.save()
        optionalPost = request.POST["post"]
        if optionalPost != "":
            newPost = Post.objects.create(post=optionalPost,thread=newThread,writer=creator)
            newThread.post_set.add(newPost)
            newThread.save()
        return redirect(reverse("forum:forum",kwargs={"forumName":request.session["forum"]})) 
            
def showThread(request,thread):
    thread=Thread.objects.get(thread=thread)
    allPost = thread.post_set.all()
    context = {"allPost":allPost,"currentThread":thread}
    return render(request,"forum/showThread.html",context)

def newPost(request):
    if request.method == "POST":
        post = request.POST["post"]
        writer = User.objects.get(username=request.session["user"])
        currentThread = request.POST["currentThread"]
        thread = Thread.objects.get(thread=currentThread)
        newPost = Post.objects.create(post=post,thread=thread,writer=writer)
        newPost.save()
        thread.post_set.add(newPost)
        thread.save()
        return redirect(reverse("forum:showThread",kwargs={"thread":currentThread}))

def newForum(request):
    if request.method == "POST":
        forumTitle = request.POST["forumTitle"]
        description = request.POST["description"]
        newForum = Forum.objects.create(forum=forumTitle,description=description)
        newForum.save()
        return redirect(reverse("forum:index"))

apps/forum/templates/forum/create.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	<form action="{%url 'forum:newForum'%}" method="post">
		{%csrf_token%}
		<input id="forum" type="text" name="forumTitle" placeholder="enter forum title">
		<textarea id="description" name="description" cols="30" rows="10"></textarea>
		<input type="submit" value="submit">
	</form>
</body>
</html>

apps/forum/templates/forum/forum.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Meow's in Need</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'forum/stylesheets/bootstrap.min.css'%}" media="all">
	<link rel="stylesheet" href="{% static 'forum/stylesheets/style2.css'%}" media="all">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			var form = $("form");
			$("button").click(function(){
				form.toggle();
			})
		})
	</script>
</head>
<body>
	<header>
		<nav><a href="{%url 'forum:index'%}">Home</a><a href="">Cats in Need</a><a href="{%url 'forum:logout'%}">Log out</a></nav>
		<ul class="breadcrumb">
			<li><img src="{%static 'forum/pictures/home.png'%}" alt="home" id="firstImage"><a href="{%url 'forum:index'%}">Home</a></li>
			<li class="active">Forum</li>
		</ul>
	</header>
	<h2>{{request.session.forum}} Forum</h2>
	<button class="btn btn-primary">New Topic</button>
	<form action="{%url 'forum:createThread'%}" method="post">
		{%csrf_token%}
		<input id="threadTitle" type="text" name="thread" placeholder="Enter thread's name"><br>
		<textarea id="post" name="post" cols="50" rows="3" placeholder="Enter first post for new thread"></textarea>
		<input type="submit" value="Submit" class="btn btn-danger">
	</form>
	<table class="table table-hover">
		<tbody>
	{% if allThread %}
	{% for thread in allThread %}
		<tr class="thread">
			<td><img src="{%static 'forum/pictures/note3.png'%}" alt="icon"> 
				<a href="{%url 'forum:showThread' thread=thread.thread%}">{{thread.thread}}</a></td>
			<td><img src="{%static 'forum/pictures/discussion.png'%}" alt="forum icon">
				{{thread.post_set.all|length}}</td>
			<td>{{thread.creator.username}}</td>
		</tr>
	{% endfor %}
	{% endif %}
		</tbody>
	</table>
</body>
</html>

apps/forum/templates/forum/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Meow's in Need</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	{% load staticfiles %}
	<link rel="stylesheet" href="{%static 'forum/stylesheets/bootstrap.min.css'%}" media="all">
	<link rel="stylesheet" href="{% static 'forum/stylesheets/style.css'%}" media="all">
	<script>
		$(document).ready(function(){
		})
	</script>
</head>
<body>
	<header>
		<img src="{%static 'forum/pictures/whitecat.jpg'%}" alt="whitecat" id="whitecat">
		<h2>Welcome to<br> Meows in Need Forum</h2>
		<nav><a href="">Home</a><a href="">Cats in Need</a><a href="">Log out</a></nav>
		<div class="breadcrumb">
			<img src="{%static 'forum/pictures/home.png'%}" alt="home"><a href="#">Forums</a>
		</div>
	</header>
	<div id="main">
		<div class="forum">
			<img src="{%static 'forum/pictures/heart.png'%}" alt="heart">
			<h3><a href="{%url 'forum:forum' forumName=health.forum%}">{{health.forum}}</a></h3>
			<p>{{health.description}}</p>
		</div>
		<div class="forum">
			<img src="{%static 'forum/pictures/food.png'%}" alt="food">
			<h3><a href="{%url 'forum:forum' forumName=nutrition.forum%}">{{nutrition.forum}}</a></h3>
			<p>{{nutrition.description}}</p>
		</div>
		<div class="forum">
			<img src="{%static 'forum/pictures/behavior.png'%}" alt="behavior">
			<h3><a href="{%url 'forum:forum' forumName=behavior.forum%}">{{behavior.forum}}</a></h3>
			<p>{{behavior.description}}</p>
		</div>
		<div class="forum">
			<img src="{%static 'forum/pictures/shower.png'%}" alt="shower">
			<h3><a href="{%url 'forum:forum' forumName=care.forum%}">{{care.forum}}</a></h3>
			<p>{{care.description}}</p>
		</div>
		<div class="forum">
			<img src="{%static 'forum/pictures/newcat.png'%}" alt="newcat">
			<h3><a href="{%url 'forum:forum' forumName=new.forum%}">{{new.forum}}</a></h3>
			<p>{{new.description}}</p>
		</div>
		<div class="forum">
			<img src="{%static 'forum/pictures/pregnant.png'%}" alt="pregnant cat">
			<h3><a href="{%url 'forum:forum' forumName=pregnant.forum%}">Pregnant Cats</a></h3>
			<p>{{pregnant.description}}</p>
		</div>
		<div class="forum">
			<img src="{%static 'forum/pictures/dog.png'%}" alt="dog">
			<h3><a href="{%url 'forum:forum' forumName=dog.forum%}">{{dog.forum}}</a></h3>
			<p>{{dog.description}}</p>
		</div>

	</div>
</body>
</html>

apps/forum/templates/forum/newThread.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Meow's in Need</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'forum/stylesheets/bootstrap.min.css'%}" media="all">
	<link rel="stylesheet" href="{%static 'forum/stylesheets/threadstyle.css'%}" media="all">
</head>
<body>
	<header>
		<img src="{% static 'forum/pictures/catLogo.png'%}" alt="cat logo">
		<h2>Help My Cats</h2>
		<a href="{% url 'forum:logout' %}">Log out</a>
	</header>
	<div id="form">
	<p>start a new thread for <strong>{{forum}}</strong> forum</p>
	<form class="form-horizontal" action="{% url 'forum:createThread'%}" method="post">
		{%csrf_token%}
		<input id="threadTitle" type="text" name="thread" placeholder="Enter thread title here">
		<textarea id="post" name="post" cols="30" rows="4" placeholder="Enter the first post for this thread(optional)"></textarea><br>
		<input type="submit" value="Submit" class="btn btn-primary">
		
	</form>
	</div>
</body>
</html>

apps/forum/templates/forum/showThread.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Meow's in Need</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	{%load staticfiles%}
	<link rel="stylesheet" href="{%static 'forum/stylesheets/bootstrap.min.css'%}" media="all">
	<link rel="stylesheet" href="{%static 'forum/stylesheets/thread.css'%}" media="all">
	<script type="text/javascript">
		$(document).ready(function(){
			var form = $("form");
			$("button").click(function(){
				form.toggle();
			})
		})
	</script>
</head>
<body>
	<header>
		<nav><a href="{%url 'forum:index'%}">Home</a><a href="">Cats in Need</a><a href="{%url 'forum:logout'%}">Log out</a></nav>
		<ul class="breadcrumb">
			<li><img src="{%static 'forum/pictures/home.png'%}" alt="home" id="firstImage"><a href="{%url 'forum:index'%}">Home</a></li>
			<li><a href="{%url 'forum:forum' forumName=request.session.forum%}">Forum</a></li>
			<li class="active">Thread</li>
		</ul>
	</header>
	<h3 id="threadTitle">{{currentThread.thread}}</h3>
	<button class="btn btn-info">Reply</button>
	<form action="{%url 'forum:newPost'%}" method="post">
		{%csrf_token%}
		<textarea id="reply" name="post" cols="60" rows="3" placeholder="Your reply ..."></textarea>
		<input type="hidden" name="currentThread" value="{{currentThread.thread}}">
		<input type="submit" value="Submit" class="btn btn-danger">
	</form>
	<table class="table" id="post">
		{% for post in allPost %}
			<tr>
				<td>{{post.writer.username}}</td>
				<td><span>{{post.created_at}}</span><br>{{post.post|linebreaksbr}}</td>
			</tr>
		{% endfor %}
	</table>
	
</body>
</html>